// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table bikes (BikepointID:string, Street:string, Neighbourhood:string, Latitude:real, Longitude:real, No_Bikes:long, No_Empty_Docks:long) 
.create-merge table ['bikes-by-street'] (Street:string, SUM_No_Bikes:real, Window_End_Time:datetime) 
